apiVersion: v1
kind: Namespace
metadata:
  name: staging
---

apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
 name: staglanding-prod
 namespace: staging
spec:
 acme:
   # The ACME server URL
   server: https://acme-v02.api.letsencrypt.org/directory
   # Email address used for ACME registration
   email: kerupuk.lovers@gmail.com
   # Name of a secret used to store the ACME account private key
   privateKeySecretRef:
     name: staglanding-prod
   # Enable the HTTP-01 challenge provider
   solvers:
   - selector: {}
     http01:
       ingress:
         class:  nginx

---

apiVersion: v1
kind: Secret
metadata:
  name: staglanding-secret
  namespace: staging
type: Opaque
data:
   DB_USER: ZGV2b3BzY2lsc3k=
   DB_PASS: MTIzNDU2Nzg5MA==
   DB_HOST: a3ViZS1wZXNidWsuY2N5Ym1pa2V6cG1jLmFwLXNvdXRoZWFzdC0xLnJkcy5hbWF6b25hd3MuY29t
   DB_NAME: ZGJzb3NtZWQ=

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: staglanding-p
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      name: staglanding-p
  template:
    metadata:
      labels:
        name: staglanding-p
    spec:
      containers:
      - name: staglanding-p
        image: raxer/landing
        env:
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: staglanding-secret
                  key: DB_USER
            - name: DB_PASS
              valueFrom:
                secretKeyRef:
                  name: staglanding-secret
                  key: DB_PASS
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: staglanding-secret
                  key: DB_HOST
            - name: DB_NAME
              valueFrom:
                secretKeyRef:
                  name: staglanding-secret
                  key: DB_NAME
---
apiVersion: v1
kind: Service
metadata:
  name: staglanding-p
  namespace: staging
spec:
  #type: LoadBalancer
  ports:
    - port: 81
      #nodePort: 30080
  selector:
    name: staglanding-p
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: staglanding-p-ingress
  namespace: staging
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "staglanding-prod"
spec:
  rules:
  - host: staglanding.rafifauz.site
    http:
      paths:
      #- path: /belajar
      - backend:
          serviceName: staglanding-p
          servicePort: 81
  
  tls:
  - hosts:
    - staglanding.rafifauz.site
    secretName: staglanding-tls

        
